services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: my-rabbit
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port for AMQP
      - "15672:15672" # RabbitMQ management UI

  receiver:
    image: receiver:0.1.0-SNAPSHOT
    container_name: receiver
